# Generated by Django 5.0 on 2024-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_cfp_link_homepage_sponsor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_call_to_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
