# Generated by Django 5.0.9 on 2024-11-30 12:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_banner_call_to_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(default='00:00')),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField(default='23:59')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='home.homepage')),
            ],
        ),
    ]
